### ISSUE TITLE
java.io.IOException: Failed to extract dlang-build.tar.gz - Text file busy

### ISSUE THREAD

**Issue by wilzbach** [dlang/ci#161]
```
remote file operation failed: /var/lib/jenkins/dlang_projects@6 at hudson.remoting.Channel@f787666:JNLP4-connect connection from 201.62.205.35.bc.googleusercontent.com/35.205.62.201:45376: java.io.IOException: Failed to extract dlang-build.tar.gz
```

Seen here:

https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fdmd/detail/PR-7831/1/pipeline

Full exception:

```
java.nio.file.FileSystemException: /var/lib/jenkins/dlang_projects@6/distribution/bin/dmd: Text file busy
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
	at java.nio.file.Files.newOutputStream(Files.java:216)
	at hudson.util.IOUtils.copy(IOUtils.java:39)
	at hudson.FilePath.readFromTar(FilePath.java:2307)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 201.62.205.35.bc.googleusercontent.com/35.205.62.201:45376
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1693)
		at hudson.remoting.UserResponse.retrieve(UserRequest.java:310)
		at hudson.remoting.Channel.call(Channel.java:908)
		at hudson.FilePath.act(FilePath.java:986)
		at hudson.FilePath.act(FilePath.java:975)
		at hudson.FilePath.untar(FilePath.java:528)
		at org.jenkinsci.plugins.workflow.flow.StashManager.unstash(StashManager.java:129)
		at org.jenkinsci.plugins.workflow.support.steps.stash.UnstashStep$Execution.run(UnstashStep.java:74)
		at org.jenkinsci.plugins.workflow.support.steps.stash.UnstashStep$Execution.run(UnstashStep.java:61)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
		at hudson.security.ACL.impersonate(ACL.java:260)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Caused: java.io.IOException: Failed to extract dlang-build.tar.gz
	at hudson.FilePath.readFromTar(FilePath.java:2317)
	at hudson.FilePath.access$400(FilePath.java:196)
	at hudson.FilePath$4.invoke(FilePath.java:530)
	at hudson.FilePath$4.invoke(FilePath.java:528)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2760)
	at hudson.remoting.UserRequest.perform(UserRequest.java:207)
	at hudson.remoting.UserRequest.perform(UserRequest.java:53)
	at hudson.remoting.Request$2.run(Request.java:358)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1$1.run(Engine.java:98)
Caused: java.io.IOException: remote file operation failed: /var/lib/jenkins/dlang_projects@6 at hudson.remoting.Channel@f787666:JNLP4-connect connection from 201.62.205.35.bc.googleusercontent.com/35.205.62.201:45376
	at hudson.FilePath.act(FilePath.java:993)
	at hudson.FilePath.act(FilePath.java:975)
	at hudson.FilePath.untar(FilePath.java:528)
```

Is this due to `unstash name: 'dlang-build'` happening in parallel?

**Comment by wilzbach** [comment]
I see this in the log:

```
[DlangScience/scid] Running on runner-01.ci.lxd in /var/lib/jenkins/dlang_projects@3
[Pipeline] [DlangScience/scid] unstash
[Pipeline] [Netflix/vectorflow] echo
[Netflix/vectorflow] Running on runner-01-gce in /var/lib/jenkins/dlang_projects
[Pipeline] [Netflix/vectorflow] unstash
[Pipeline] [PhilippeSigaud/Pegged] echo
[PhilippeSigaud/Pegged] Running on runner-01-gce in /var/lib/jenkins/dlang_projects@4
[Pipeline] [PhilippeSigaud/Pegged] unstash
[Pipeline] [ariovistus/pyd] echo
[ariovistus/pyd] Running on runner-01-gce in /var/lib/jenkins/dlang_projects@5
[Pipeline] [ariovistus/pyd] unstash
[Pipeline] [dlang/undeaD] echo
[dlang/undeaD] Running on runner-01-gce in /var/lib/jenkins/dlang_projects@8
[Pipeline] [dlang/undeaD] unstash
[Pipeline] [economicmodeling/containers] echo
[economicmodeling/containers] Running on runner-01.ci.lxd in /var/lib/jenkins/dlang_projects@4
[Pipeline] [economicmodeling/containers] unstash
[Pipeline] [kyllingstad/zmqd] echo
[kyllingstad/zmqd] Running on runner-02.ci.lxd in /var/lib/jenkins/dlang_projects@4
```


```
[vibe-d/vibe.d+vibe-core-examples] Running in /var/lib/jenkins/dlang_projects@6
[Pipeline] [vibe-d/vibe.d+vibe-core-examples] {
[Pipeline] [vibe-d/vibe.d+libevent-examples] echo
[vibe-d/vibe.d+libevent-examples] Running on runner-01-gce in /var/lib/jenkins/dlang_projects@2
[Pipeline] [vibe-d/vibe.d+libevent-examples] unstash
[Pipeline] [vibe-d/vibe.d+vibe-core-examples] echo
[vibe-d/vibe.d+vibe-core-examples] Running on runner-01-gce in /var/lib/jenkins/dlang_projects@6
```

`dlang_projects@6` only appears for the vibe-d/vibe.d+vibe-core-examples test.

**Comment by wilzbach** [comment]
seen here too:

https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fdmd/detail/PR-7866/1/pipeline

```
java.nio.file.FileSystemException: /var/lib/jenkins/dlang_projects/distribution/bin/dmd: Text file busy
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
	at java.nio.file.Files.newOutputStream(Files.java:216)
	at hudson.util.IOUtils.copy(IOUtils.java:39)
	at hudson.FilePath.readFromTar(FilePath.java:2307)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from ci.dlang.io/163.172.106.61:36274
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1693)
		at hudson.remoting.UserResponse.retrieve(UserRequest.java:310)
		at hudson.remoting.Channel.call(Channel.java:908)
		at hudson.FilePath.act(FilePath.java:986)
		at hudson.FilePath.act(FilePath.java:975)
		at hudson.FilePath.untar(FilePath.java:528)
		at org.jenkinsci.plugins.workflow.flow.StashManager.unstash(StashManager.java:129)
		at org.jenkinsci.plugins.workflow.support.steps.stash.UnstashStep$Execution.run(UnstashStep.java:74)
		at org.jenkinsci.plugins.workflow.support.steps.stash.UnstashStep$Execution.run(UnstashStep.java:61)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
		at hudson.security.ACL.impersonate(ACL.java:260)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Caused: java.io.IOException: Failed to extract dlang-build.tar.gz
	at hudson.FilePath.readFromTar(FilePath.java:2317)
```

**Comment by acmnu** [comment]
@wilzbach I am not a fun of Dlang man, but I am here from google search to like your comment.
